# Generated by Django 3.1.5 on 2021-01-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=70)),
                ('child_age', models.IntegerField(default=0)),
                ('child_dob', models.DateField()),
                ('child_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('mother_name', models.CharField(max_length=70, verbose_name='mother name')),
                ('mother_age', models.IntegerField(default=0)),
            ],
        ),
    ]
