# Generated by Django 3.1.5 on 2021-01-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='child_gender',
            field=models.CharField(choices=[('S', 'Select'), ('M', 'Male'), ('F', 'Female')], default='M', max_length=6),
        ),
    ]
